// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserFriends = `-- name: CountUserFriends :one
SELECT COUNT(*) FROM friends 
WHERE (sender_id = $1 OR receiver_id = $1) AND status = 'accepted'
`

func (q *Queries) CountUserFriends(ctx context.Context, senderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserFriends, senderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friends
WHERE (sender_id = $1 AND receiver_id = $2)
   OR (sender_id = $2 AND receiver_id = $1)
`

type DeleteFriendshipParams struct {
	SenderID   pgtype.UUID `json:"sender_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.SenderID, arg.ReceiverID)
	return err
}

const getFriendRequestsList = `-- name: GetFriendRequestsList :many
SELECT f.id as request_id, f.sender_id, f.receiver_id, f.status, f.created_at,
       u.id as user_id, u.username, u.avatar_url, u.elo, u.wins, u.matches_played, u.online_status
FROM friends f
JOIN users u ON 
  (f.sender_id = $1 AND u.id = f.receiver_id) OR
  (f.receiver_id = $1 AND u.id = f.sender_id)
WHERE f.status = 'pending' AND (f.sender_id = $1 OR f.receiver_id = $1)
`

type GetFriendRequestsListRow struct {
	RequestID     pgtype.UUID        `json:"request_id"`
	SenderID      pgtype.UUID        `json:"sender_id"`
	ReceiverID    pgtype.UUID        `json:"receiver_id"`
	Status        FriendStatus       `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UserID        pgtype.UUID        `json:"user_id"`
	Username      string             `json:"username"`
	AvatarUrl     string             `json:"avatar_url"`
	Elo           int32              `json:"elo"`
	Wins          int32              `json:"wins"`
	MatchesPlayed int32              `json:"matches_played"`
	OnlineStatus  bool               `json:"online_status"`
}

func (q *Queries) GetFriendRequestsList(ctx context.Context, senderID pgtype.UUID) ([]GetFriendRequestsListRow, error) {
	rows, err := q.db.Query(ctx, getFriendRequestsList, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendRequestsListRow
	for rows.Next() {
		var i GetFriendRequestsListRow
		if err := rows.Scan(
			&i.RequestID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Status,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
			&i.AvatarUrl,
			&i.Elo,
			&i.Wins,
			&i.MatchesPlayed,
			&i.OnlineStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, sender_id, receiver_id, status, created_at, updated_at FROM friends 
WHERE (sender_id = $1 AND receiver_id = $2) 
   OR (sender_id = $2 AND receiver_id = $1)
LIMIT 1
`

type GetFriendshipParams struct {
	SenderID   pgtype.UUID `json:"sender_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friend, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.SenderID, arg.ReceiverID)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFriendsPaginated = `-- name: ListFriendsPaginated :many
SELECT u.id, u.username, u.avatar_url, u.elo, u.wins, u.matches_played, u.online_status, f.status
FROM friends f
JOIN users u ON
  (f.sender_id = $1 AND u.id = f.receiver_id) OR
  (f.receiver_id = $1 AND u.id = f.sender_id)
WHERE f.status = 'accepted' AND (u.id > $2 OR $2 IS NULL)
ORDER BY u.online_status DESC, u.elo DESC, u.id ASC
LIMIT $3
`

type ListFriendsPaginatedParams struct {
	SenderID pgtype.UUID `json:"sender_id"`
	ID       pgtype.UUID `json:"id"`
	Limit    int32       `json:"limit"`
}

type ListFriendsPaginatedRow struct {
	ID            pgtype.UUID  `json:"id"`
	Username      string       `json:"username"`
	AvatarUrl     string       `json:"avatar_url"`
	Elo           int32        `json:"elo"`
	Wins          int32        `json:"wins"`
	MatchesPlayed int32        `json:"matches_played"`
	OnlineStatus  bool         `json:"online_status"`
	Status        FriendStatus `json:"status"`
}

func (q *Queries) ListFriendsPaginated(ctx context.Context, arg ListFriendsPaginatedParams) ([]ListFriendsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listFriendsPaginated, arg.SenderID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsPaginatedRow
	for rows.Next() {
		var i ListFriendsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.Elo,
			&i.Wins,
			&i.MatchesPlayed,
			&i.OnlineStatus,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendFriendRequest = `-- name: SendFriendRequest :one
INSERT INTO friends (sender_id, receiver_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, sender_id, receiver_id, status, created_at, updated_at
`

type SendFriendRequestParams struct {
	SenderID   pgtype.UUID `json:"sender_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
}

func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) (Friend, error) {
	row := q.db.QueryRow(ctx, sendFriendRequest, arg.SenderID, arg.ReceiverID)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFriendStatus = `-- name: UpdateFriendStatus :exec
UPDATE friends
SET status = $3, updated_at = NOW()
WHERE (sender_id = $1 AND receiver_id = $2)
   OR (sender_id = $2 AND receiver_id = $1)
`

type UpdateFriendStatusParams struct {
	SenderID   pgtype.UUID  `json:"sender_id"`
	ReceiverID pgtype.UUID  `json:"receiver_id"`
	Status     FriendStatus `json:"status"`
}

func (q *Queries) UpdateFriendStatus(ctx context.Context, arg UpdateFriendStatusParams) error {
	_, err := q.db.Exec(ctx, updateFriendStatus, arg.SenderID, arg.ReceiverID, arg.Status)
	return err
}
