// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChallengeStatus string

const (
	ChallengeStatusPending  ChallengeStatus = "pending"
	ChallengeStatusAccepted ChallengeStatus = "accepted"
	ChallengeStatusDeclined ChallengeStatus = "declined"
	ChallengeStatusExpired  ChallengeStatus = "expired"
)

func (e *ChallengeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengeStatus(s)
	case string:
		*e = ChallengeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengeStatus: %T", src)
	}
	return nil
}

type NullChallengeStatus struct {
	ChallengeStatus ChallengeStatus `json:"challenge_status"`
	Valid           bool            `json:"valid"` // Valid is true if ChallengeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengeStatus), nil
}

type FriendStatus string

const (
	FriendStatusPending  FriendStatus = "pending"
	FriendStatusAccepted FriendStatus = "accepted"
	FriendStatusBlocked  FriendStatus = "blocked"
)

func (e *FriendStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendStatus(s)
	case string:
		*e = FriendStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendStatus: %T", src)
	}
	return nil
}

type NullFriendStatus struct {
	FriendStatus FriendStatus `json:"friend_status"`
	Valid        bool         `json:"valid"` // Valid is true if FriendStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendStatus), nil
}

type GameMode string

const (
	GameModeArithmetic GameMode = "arithmetic"
	GameModeMemory     GameMode = "memory"
	GameModeOperator   GameMode = "operator"
)

func (e *GameMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameMode(s)
	case string:
		*e = GameMode(s)
	default:
		return fmt.Errorf("unsupported scan type for GameMode: %T", src)
	}
	return nil
}

type NullGameMode struct {
	GameMode GameMode `json:"game_mode"`
	Valid    bool     `json:"valid"` // Valid is true if GameMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameMode) Scan(value interface{}) error {
	if value == nil {
		ns.GameMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameMode), nil
}

type NotificationType string

const (
	NotificationTypeFriendRequest     NotificationType = "friend_request"
	NotificationTypeFriendAccepted    NotificationType = "friend_accepted"
	NotificationTypeChallengeIn       NotificationType = "challenge_in"
	NotificationTypeChallengeDeclined NotificationType = "challenge_declined"
	NotificationTypeWeeklyReset       NotificationType = "weekly_reset"
	NotificationTypeReengagement      NotificationType = "reengagement"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type PlatformType string

const (
	PlatformTypeIos     PlatformType = "ios"
	PlatformTypeAndroid PlatformType = "android"
)

func (e *PlatformType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlatformType(s)
	case string:
		*e = PlatformType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlatformType: %T", src)
	}
	return nil
}

type NullPlatformType struct {
	PlatformType PlatformType `json:"platform_type"`
	Valid        bool         `json:"valid"` // Valid is true if PlatformType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlatformType) Scan(value interface{}) error {
	if value == nil {
		ns.PlatformType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlatformType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlatformType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlatformType), nil
}

type SocialPlatform string

const (
	SocialPlatformInstagram SocialPlatform = "instagram"
	SocialPlatformTwitter   SocialPlatform = "twitter"
	SocialPlatformGithub    SocialPlatform = "github"
	SocialPlatformLinkedin  SocialPlatform = "linkedin"
	SocialPlatformYoutube   SocialPlatform = "youtube"
)

func (e *SocialPlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SocialPlatform(s)
	case string:
		*e = SocialPlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for SocialPlatform: %T", src)
	}
	return nil
}

type NullSocialPlatform struct {
	SocialPlatform SocialPlatform `json:"social_platform"`
	Valid          bool           `json:"valid"` // Valid is true if SocialPlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSocialPlatform) Scan(value interface{}) error {
	if value == nil {
		ns.SocialPlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SocialPlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSocialPlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SocialPlatform), nil
}

type Challenge struct {
	ID           pgtype.UUID        `json:"id"`
	ChallengerID pgtype.UUID        `json:"challenger_id"`
	ChallengedID pgtype.UUID        `json:"challenged_id"`
	Mode         GameMode           `json:"mode"`
	Status       ChallengeStatus    `json:"status"`
	MatchID      pgtype.UUID        `json:"match_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type FcmToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	FcmToken   string             `json:"fcm_token"`
	Platform   PlatformType       `json:"platform"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Friend struct {
	ID         pgtype.UUID        `json:"id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID        `json:"receiver_id"`
	Status     FriendStatus       `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type LeaderboardSnapshot struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Mode      GameMode           `json:"mode"`
	WeekStart pgtype.Date        `json:"week_start"`
	Score     int32              `json:"score"`
	Rank      int32              `json:"rank"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	ID             pgtype.UUID        `json:"id"`
	Player1ID      pgtype.UUID        `json:"player1_id"`
	Player2ID      pgtype.UUID        `json:"player2_id"`
	Mode           GameMode           `json:"mode"`
	WinnerID       pgtype.UUID        `json:"winner_id"`
	IsBotMatch     bool               `json:"is_bot_match"`
	Player1Answers []byte             `json:"player1_answers"`
	Player2Answers []byte             `json:"player2_answers"`
	ForfeitByID    pgtype.UUID        `json:"forfeit_by_id"`
	PlayedAt       pgtype.Timestamptz `json:"played_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      NotificationType   `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Data      []byte             `json:"data"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationPreference struct {
	UserID            pgtype.UUID        `json:"user_id"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FriendRequest     bool               `json:"friend_request"`
	FriendAccepted    bool               `json:"friend_accepted"`
	ChallengeReceived bool               `json:"challenge_received"`
	ChallengeDeclined bool               `json:"challenge_declined"`
	Reengagement      bool               `json:"reengagement"`
	WeeklyReset       bool               `json:"weekly_reset"`
	GlobalMute        bool               `json:"global_mute"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	GoogleID      string             `json:"google_id"`
	Username      string             `json:"username"`
	AvatarUrl     string             `json:"avatar_url"`
	Bio           pgtype.Text        `json:"bio"`
	Country       pgtype.Text        `json:"country"`
	Dob           pgtype.Date        `json:"dob"`
	Elo           int32              `json:"elo"`
	Wins          int32              `json:"wins"`
	Losses        int32              `json:"losses"`
	MatchesPlayed int32              `json:"matches_played"`
	BestStreak    int32              `json:"best_streak"`
	CurrentStreak int32              `json:"current_streak"`
	Xp            int32              `json:"xp"`
	FavMode       NullGameMode       `json:"fav_mode"`
	IsBot         bool               `json:"is_bot"`
	OnlineStatus  bool               `json:"online_status"`
	LastSeen      pgtype.Timestamptz `json:"last_seen"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserSocialLink struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Platform  SocialPlatform     `json:"platform"`
	Url       string             `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UsernameChange struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	OldUsername string             `json:"old_username"`
	NewUsername string             `json:"new_username"`
	ChangedAt   pgtype.Timestamptz `json:"changed_at"`
}
