// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFCMToken = `-- name: DeleteFCMToken :exec
DELETE FROM fcm_tokens WHERE fcm_token = $1
`

func (q *Queries) DeleteFCMToken(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, deleteFCMToken, fcmToken)
	return err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, updated_at, friend_request, friend_accepted, challenge_received, challenge_declined, reengagement, weekly_reset, global_mute FROM notification_preferences WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.UpdatedAt,
		&i.FriendRequest,
		&i.FriendAccepted,
		&i.ChallengeReceived,
		&i.ChallengeDeclined,
		&i.Reengagement,
		&i.WeeklyReset,
		&i.GlobalMute,
	)
	return i, err
}

const getUserFCMTokens = `-- name: GetUserFCMTokens :many
SELECT fcm_token FROM fcm_tokens WHERE user_id = $1
`

func (q *Queries) GetUserFCMTokens(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserFCMTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fcm_token string
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (user_id, type, title, body, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, data, is_read, created_at
`

type InsertNotificationParams struct {
	UserID pgtype.UUID      `json:"user_id"`
	Type   NotificationType `json:"type"`
	Title  string           `json:"title"`
	Body   string           `json:"body"`
	Data   []byte           `json:"data"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsPaginated = `-- name: ListNotificationsPaginated :many
SELECT id, user_id, type, title, body, data, is_read, created_at FROM notifications 
WHERE user_id = $1 AND (id < $2 OR $2 IS NULL)
ORDER BY created_at DESC
LIMIT $3
`

type ListNotificationsPaginatedParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListNotificationsPaginated(ctx context.Context, arg ListNotificationsPaginatedParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsPaginated, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = true WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = true WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const registerFCMToken = `-- name: RegisterFCMToken :exec
INSERT INTO fcm_tokens (user_id, fcm_token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (fcm_token) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    updated_at = NOW()
`

type RegisterFCMTokenParams struct {
	UserID   pgtype.UUID  `json:"user_id"`
	FcmToken string       `json:"fcm_token"`
	Platform PlatformType `json:"platform"`
}

func (q *Queries) RegisterFCMToken(ctx context.Context, arg RegisterFCMTokenParams) error {
	_, err := q.db.Exec(ctx, registerFCMToken, arg.UserID, arg.FcmToken, arg.Platform)
	return err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (
    user_id, friend_request, friend_accepted, challenge_received, 
    challenge_declined, reengagement, weekly_reset, global_mute
) VALUES (
    $1, 
    COALESCE($2, true),
    COALESCE($3, true),
    COALESCE($4, true),
    COALESCE($5, true),
    COALESCE($6, true),
    COALESCE($7, true),
    COALESCE($8, false)
)
ON CONFLICT (user_id) DO UPDATE SET
    friend_request = COALESCE($2, notification_preferences.friend_request),
    friend_accepted = COALESCE($3, notification_preferences.friend_accepted),
    challenge_received = COALESCE($4, notification_preferences.challenge_received),
    challenge_declined = COALESCE($5, notification_preferences.challenge_declined),
    reengagement = COALESCE($6, notification_preferences.reengagement),
    weekly_reset = COALESCE($7, notification_preferences.weekly_reset),
    global_mute = COALESCE($8, notification_preferences.global_mute),
    updated_at = NOW()
RETURNING user_id, updated_at, friend_request, friend_accepted, challenge_received, challenge_declined, reengagement, weekly_reset, global_mute
`

type UpsertNotificationPreferencesParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	FriendRequest     interface{} `json:"friend_request"`
	FriendAccepted    interface{} `json:"friend_accepted"`
	ChallengeReceived interface{} `json:"challenge_received"`
	ChallengeDeclined interface{} `json:"challenge_declined"`
	Reengagement      interface{} `json:"reengagement"`
	WeeklyReset       interface{} `json:"weekly_reset"`
	GlobalMute        interface{} `json:"global_mute"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.FriendRequest,
		arg.FriendAccepted,
		arg.ChallengeReceived,
		arg.ChallengeDeclined,
		arg.Reengagement,
		arg.WeeklyReset,
		arg.GlobalMute,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.UpdatedAt,
		&i.FriendRequest,
		&i.FriendAccepted,
		&i.ChallengeReceived,
		&i.ChallengeDeclined,
		&i.Reengagement,
		&i.WeeklyReset,
		&i.GlobalMute,
	)
	return i, err
}
