// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsernameChangesPast30Days = `-- name: CountUsernameChangesPast30Days :one
SELECT COUNT(*) FROM username_changes 
WHERE user_id = $1 AND changed_at > NOW() - INTERVAL '30 days'
`

func (q *Queries) CountUsernameChangesPast30Days(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsernameChangesPast30Days, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSocialLink = `-- name: DeleteSocialLink :exec
DELETE FROM user_social_links WHERE user_id = $1 AND platform = $2
`

type DeleteSocialLinkParams struct {
	UserID   pgtype.UUID    `json:"user_id"`
	Platform SocialPlatform `json:"platform"`
}

func (q *Queries) DeleteSocialLink(ctx context.Context, arg DeleteSocialLinkParams) error {
	_, err := q.db.Exec(ctx, deleteSocialLink, arg.UserID, arg.Platform)
	return err
}

const getLatestUsernameChange = `-- name: GetLatestUsernameChange :one
SELECT changed_at FROM username_changes
WHERE user_id = $1
ORDER BY changed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestUsernameChange(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestUsernameChange, userID)
	var changed_at pgtype.Timestamptz
	err := row.Scan(&changed_at)
	return changed_at, err
}

const getSocialLinksByUserID = `-- name: GetSocialLinksByUserID :many
SELECT id, user_id, platform, url, created_at, updated_at FROM user_social_links WHERE user_id = $1
`

func (q *Queries) GetSocialLinksByUserID(ctx context.Context, userID pgtype.UUID) ([]UserSocialLink, error) {
	rows, err := q.db.Query(ctx, getSocialLinksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSocialLink
	for rows.Next() {
		var i UserSocialLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, username, avatar_url, bio, country, dob, elo, wins, losses, matches_played, best_streak, current_streak, xp, fav_mode, is_bot, online_status, last_seen, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Country,
		&i.Dob,
		&i.Elo,
		&i.Wins,
		&i.Losses,
		&i.MatchesPlayed,
		&i.BestStreak,
		&i.CurrentStreak,
		&i.Xp,
		&i.FavMode,
		&i.IsBot,
		&i.OnlineStatus,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, google_id, username, avatar_url, bio, country, dob, elo, wins, losses, matches_played, best_streak, current_streak, xp, fav_mode, is_bot, online_status, last_seen, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Country,
		&i.Dob,
		&i.Elo,
		&i.Wins,
		&i.Losses,
		&i.MatchesPlayed,
		&i.BestStreak,
		&i.CurrentStreak,
		&i.Xp,
		&i.FavMode,
		&i.IsBot,
		&i.OnlineStatus,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUsernameChange = `-- name: InsertUsernameChange :exec
INSERT INTO username_changes (user_id, old_username, new_username)
VALUES ($1, $2, $3)
`

type InsertUsernameChangeParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	OldUsername string      `json:"old_username"`
	NewUsername string      `json:"new_username"`
}

func (q *Queries) InsertUsernameChange(ctx context.Context, arg InsertUsernameChangeParams) error {
	_, err := q.db.Exec(ctx, insertUsernameChange, arg.UserID, arg.OldUsername, arg.NewUsername)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
  username = COALESCE($2, username),
  bio = COALESCE($3, bio),
  country = COALESCE($4, country),
  dob = COALESCE($5, dob)
WHERE id = $1
RETURNING id, google_id, username, avatar_url, bio, country, dob, elo, wins, losses, matches_played, best_streak, current_streak, xp, fav_mode, is_bot, online_status, last_seen, created_at, updated_at
`

type UpdateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Username pgtype.Text `json:"username"`
	Bio      pgtype.Text `json:"bio"`
	Country  pgtype.Text `json:"country"`
	Dob      pgtype.Date `json:"dob"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Bio,
		arg.Country,
		arg.Dob,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Country,
		&i.Dob,
		&i.Elo,
		&i.Wins,
		&i.Losses,
		&i.MatchesPlayed,
		&i.BestStreak,
		&i.CurrentStreak,
		&i.Xp,
		&i.FavMode,
		&i.IsBot,
		&i.OnlineStatus,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSocialLink = `-- name: UpsertSocialLink :one
INSERT INTO user_social_links (user_id, platform, url)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, platform) 
DO UPDATE SET url = EXCLUDED.url, updated_at = NOW()
RETURNING id, user_id, platform, url, created_at, updated_at
`

type UpsertSocialLinkParams struct {
	UserID   pgtype.UUID    `json:"user_id"`
	Platform SocialPlatform `json:"platform"`
	Url      string         `json:"url"`
}

func (q *Queries) UpsertSocialLink(ctx context.Context, arg UpsertSocialLinkParams) (UserSocialLink, error) {
	row := q.db.QueryRow(ctx, upsertSocialLink, arg.UserID, arg.Platform, arg.Url)
	var i UserSocialLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
