// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_id, username, avatar_url)
VALUES ($1, $2, $3)
RETURNING id, google_id, username, avatar_url, bio, country, dob, elo, wins, losses, matches_played, best_streak, current_streak, xp, fav_mode, is_bot, online_status, last_seen, created_at, updated_at
`

type CreateUserParams struct {
	GoogleID  string `json:"google_id"`
	Username  string `json:"username"`
	AvatarUrl string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.GoogleID, arg.Username, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Country,
		&i.Dob,
		&i.Elo,
		&i.Wins,
		&i.Losses,
		&i.MatchesPlayed,
		&i.BestStreak,
		&i.CurrentStreak,
		&i.Xp,
		&i.FavMode,
		&i.IsBot,
		&i.OnlineStatus,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, username, avatar_url, bio, country, dob, elo, wins, losses, matches_played, best_streak, current_streak, xp, fav_mode, is_bot, online_status, last_seen, created_at, updated_at FROM users WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Country,
		&i.Dob,
		&i.Elo,
		&i.Wins,
		&i.Losses,
		&i.MatchesPlayed,
		&i.BestStreak,
		&i.CurrentStreak,
		&i.Xp,
		&i.FavMode,
		&i.IsBot,
		&i.OnlineStatus,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
